doctrine:
    dbal:
        default_connection: 'default'
        connections:
            default:
                driver: 'pdo_pgsql'
                dbname: '%env(resolve:POSTGRES_DB)%'
                host: '%env(resolve:POSTGRES_HOST)%'
                user: '%env(resolve:POSTGRES_USER)%'
                password: '%env(resolve:POSTGRES_PASSWORD)%'

